import test from 'node:test';
import assert from 'node:assert/strict';
import { createMatch, stepMatch, cellIndex, spawnItem, publicView, priority } from '../src/game/engine.js';
import { decideBot, createBotMemory } from '../src/ai/bots.js';
import { configuration, fixture, item, land } from './helpers.js';

test('UT-001: four players, distinct corners, initial paint and three valid seals',()=>{const state=createMatch({seed:42,humanCharacter:'dam',config:configuration()});assert.equal(state.owners.length,64);assert.equal(state.players[0].characterId,'dam');assert.equal(new Set(state.players.map(p=>cellIndex(p.cell))).size,4);assert.deepEqual(state.players.map(p=>p.score),[0,0,0,0]);assert.equal(state.owners.filter(x=>x!==null).length,4);assert.equal(state.items.length,3);for(const i of state.items)assert.ok(state.players.every(p=>Math.abs(p.cell.row-i.cell.row)+Math.abs(p.cell.col-i.cell.col)>1));});
test('UT-002: wall changes aim without repainting or jumping',()=>{const state=fixture();stepMatch(state,{0:{direction:'north'}});assert.equal(state.players[0].facing,'north');assert.equal(state.players[0].hop,null);assert.equal(state.owners[0],null);stepMatch(state,{0:{direction:'east'}});assert.deepEqual(state.players[0].hop.to,{row:0,col:1});});
test('UT-003: fixed hop destination; direction change applies to next jump only',()=>{const state=fixture();stepMatch(state,{0:{direction:'east'}});assert.equal(state.players[0].hop.durationTicks,36);for(let i=0;i<36;i++)stepMatch(state,{0:{direction:'south'}});assert.deepEqual(state.players[0].cell,{row:0,col:1});stepMatch(state,{0:{direction:'south'}});assert.deepEqual(state.players[0].hop.to,{row:1,col:1});});
test('UT-004: territory theft and revisiting never change guaranteed score',()=>{const state=fixture();state.owners[1]=1;state.players[0].score=7;state.players[1].score=9;land(state,0,0,1);stepMatch(state);assert.equal(state.owners[1],0);assert.deepEqual(state.players.slice(0,2).map(p=>p.score),[7,9]);land(state,0,0,1);stepMatch(state);assert.equal(state.owners.filter(p=>p===0).length,1);});
test('UT-005: landing paints before conversion, including disconnected territory',()=>{const state=fixture();for(const i of [2,3,40,60])state.owners[i]=0;state.owners[9]=1;const other=item(state,'seal',6,6);item(state,'seal',0,1);land(state,0,0,1);stepMatch(state);assert.equal(state.players[0].score,5);assert.equal(state.owners.filter(p=>p===0).length,0);assert.equal(state.owners[9],1);assert.ok(state.items.includes(other));});
test('UT-006: simultaneous landing has one collector, circular priority varies',()=>{const state=fixture();item(state,'seal',3,3);land(state,0,3,3);land(state,1,3,3);stepMatch(state);assert.equal(state.players.reduce((sum,p)=>sum+p.score,0),1);assert.equal(state.events.filter(e=>e.payload.type==='item-collected').length,1);state.tick=2;const first=priority(state,[0,1])[0];state.tick=3;assert.notEqual(priority(state,[0,1])[0],first);});
test('UT-007: exact final tick rejects collection and result is idempotent',()=>{const state=fixture();state.tick=5399;item(state,'seal',0,1);land(state,0,0,1,5400);stepMatch(state);assert.equal(state.players[0].score,0);assert.deepEqual(state.result.winnerIds,[0,1,2,3]);const snapshot=structuredClone(state);stepMatch(state,{0:{direction:'east'}});assert.deepEqual(state,snapshot);const before=fixture();before.tick=5398;item(before,'seal',0,1);land(before,0,0,1,5399);stepMatch(before);assert.equal(before.players[0].score,1);});
test('UT-008: seals wait 800ms and retain a due spawn while no cell is valid',()=>{const state=fixture();state.tick=99;item(state,'seal',0,1);land(state,0,0,1,100);stepMatch(state);assert.equal(state.pendingSealSpawns[0].dueTick,148);for(let i=0;i<47;i++)stepMatch(state);assert.equal(state.items.length,0);for(let row=0;row<8;row++)for(let col=0;col<8;col++)item(state,'impulse',row,col);stepMatch(state);assert.equal(state.pendingSealSpawns.length,1);state.items=[];stepMatch(state);assert.equal(state.pendingSealSpawns.length,0);assert.equal(state.items[0].kind,'seal');});
test('UT-009: identical seeds and input log give identical state and zero normalizes',()=>{const a=createMatch({seed:42,config:configuration()}),b=createMatch({seed:42,config:configuration()});for(let i=0;i<600;i++){const input={0:{direction:i%120<60?'east':'south'}};stepMatch(a,input);publicView(a);stepMatch(b,input);}assert.deepEqual(a,b);assert.equal(createMatch({seed:0,config:configuration()}).seed,1);});
test('IT-001: real bots move, paint, convert and finish a full round with invariants',()=>{const state=createMatch({seed:42,config:configuration()});const memories=state.players.map(()=>createBotMemory());let converted=false;for(let i=0;i<5400;i++){const view=publicView(state),inputs={};for(let id=1;id<4;id++){const decision=decideBot(view,id,memories[id],state.config.bots.standard);memories[id]=decision.memory;inputs[id]=decision.input;}stepMatch(state,inputs);converted ||= state.players.some(p=>p.score>0);assert.ok(state.owners.every(p=>p===null||[0,1,2,3].includes(p)));}assert.equal(state.status,'finished');assert.ok(converted);});
